### ISSUE TITLE
Overlays not displaying correctly

### ISSUE THREAD

**Issue by TheChymera** [neurolabusc/MRIcroGL#2]
While testing your software on multiple linux machines (I am working on packaing it for Gentoo Linux) I noticed two issues with it. These issues persist both with my Gentoo Linux build of your sources, and with your precompiled binaries:
- The MRIcronGL interface does not work with gtk3 - `ldd` tells me it uses gtk2 `libgtk-x11-2.0.so.0 => /usr/lib64/libgtk-x11-2.0.so.0 (0x00007f13bb3e2000)`, is there any way to build it for gtk3?
- Overlays do not work. I tired importing one or more overlays, and I get an additional colorbar for each, but no actual picture is being displayed. I have checked that the overlay and base image are in the same coordinate space, and tried to play arounf with most of the sliders.

Please see the following screnshots for examples (the second image should have the third image overlaid on it):

![screenshot from 2016-02-23 13-59-33](https://cloud.githubusercontent.com/assets/950524/13253396/222e0ac0-da3c-11e5-9d44-35d078d16038.png) 
![screenshot from 2016-02-23 13-09-25](https://cloud.githubusercontent.com/assets/950524/13253400/2893efe2-da3c-11e5-9aca-7e96929cfe51.png)
![screenshot from 2016-02-23 14-47-48](https://cloud.githubusercontent.com/assets/950524/13253446/6f05bfaa-da3c-11e5-8855-ee2a68ce124f.png)

**Comment by neurolabusc** [comment]
1.) I distribute with GTK2 since that is the stable release for Lazarus. Last I checked GTK3 was listed as alpha quality. If you want to validate GTK3 I would suggest downloading the latest Lazarus (1.6) as well as the MRIcroGL source code. Once Lazarus is installed you might be able to compile my code with the command
   lazbuild ./simplelaz.lpr --ws=gtk3

2.) Does the map overlay with other tools like MRIcron, and appear in register with SPM's "Check Reg" function? If yes, can you send me a sample of your images, if not you will want to check the image header's image transformation matrix. 

3.) My software tends to assume images aligned to Talairach coordinates, where the Z axis is the head-foot dimension (shown as the white-dark faces of the color cube). Your images seem to correspond with the Paxinos coordinates.... 
http://www.frontiersin.org/files/Articles/85735/fninf-08-00074-r2/image_m/fninf-08-00074-g003.jpg
It might be nice to have adapt my software to account for this (I already put in a  similar preference for my Surf Ice viewer).

**Comment by TheChymera** [comment]
1) Ok, so, compiling MRIcroGL with lazarus-1.6.0 works, but using `--ws=gtk3` does not (and I get [this error](https://bpaste.net/show/41058b1a5479)). Compiling with `--ws=gtk3` also fails with lazarus-1.2.6 (where I get what I assume was the [alpha warning you were talking about](https://bpaste.net/show/3622f69e6168)) Can you help me debug this?

2) The overlays display correctly with FSLView and fiji (imagej):
![fsl](https://cloud.githubusercontent.com/assets/950524/13315756/039ec316-dbad-11e5-83d9-fbe762db6221.png)
![na_overlay_thr10](https://cloud.githubusercontent.com/assets/950524/13315755/039b67b6-dbad-11e5-9f66-4dd7ab864160.PNG)

They do, however, also not display with MRIcron. I am guessing maybe there is some alignment issue with the images (I have seen in the past that MRIcron rigorously takes into account image position, whereas FSLView tries to center stuff) - but the headers of the images (including qform/sform) look identical. Am I missing something?

2.1) Now that I look at my colorbars - maybe it is an issue of intensity?

**Comment by neurolabusc** [comment]
1.) It looks like you are using fpc 2.6.4, whereas you need fpc and fpc-src 3.0.0 (http://www.lazarus-ide.org). I can not help you compile to GTK3 since the versions of FSL that support FSL acceleration are GTK2 only. However, I do not think GTK3 will give you any benefits: the GUI seems to be running fine for you and the graphics are done in a raw OpenGL context. 

2.) I suspect that FSLview is not replacing the images based on the spatial transforms in the header. You could check by typing "fslhd image1" and "fslhd image2" and looking at the qform and form values. In any case, why don't you email me your example dataset.

**Comment by TheChymera** [comment]
1) I guess the issue is that gtk2 does not understand hidpi (properly) - so the interface is all bunchec up (as you can see in my examples above). This is happening on a 14" laptop, so those interface elements are barely clickable.

2) I checked the headers. And yes, I'm happy to show you the data - it's [here](http://chymera.eu/NIhelp/mricrogl_overlay.tar.gz) - only I thought I had already linked it.

**Comment by neurolabusc** [comment]
1.) What version of Gentoo are you using?
  http://distrowatch.com/table.php?distribution=gentoo
I can try to run it in virtual box.

2.) OK.

**Comment by neurolabusc** [comment]
The issue here is that the images do not overlap at all.FSLView and Fiji are ignoring this fact. Like SPM, my software uses the spatial transforms stored in the NIfTI header. This allows them to align images that are resliced to different resolutions, bounding boxes and orientations.

You could either chorister one image to the other or just copy the spatial transforms in the headers:

fslhd rQBI_annotation_short.nii.gz
fslhd  QBI_atlas100.nii.gz 
....
qform_name     Unknown
qform_code     0
qto_xyz:1      1.200000  0.000000  0.000000  0.000000
qto_xyz:2      0.000000  1.200000  0.000000  0.000000
qto_xyz:3      0.000000  0.000000  1.200000  0.000000
qto_xyz:4      0.000000  0.000000  0.000000  1.000000

fslhd rIC_NA_zerbi_151130_thr10.nii.gz 
...
qform_name     Scanner Anat
qform_code     1
qto_xyz:1      1.200000  0.000000  0.000000  -100.800003
qto_xyz:2      0.000000  1.200000  0.000000  -74.400002
qto_xyz:3      0.000000  0.000000  1.200000  5.599998
qto_xyz:4      0.000000  0.000000  0.000000  1.000000

**Comment by TheChymera** [comment]
1) Gentoo is not versioned, it's a rolling release thing. So what matters are the actual software versions. Though I believe those are irrelevant as well save for using gnome-3\* . Just for reference, should you be able to start up Gentoo in a WM, I am using `gnom-base/gnome-3.18.0` and `dev-lang/lazarus-1.2.6` . You can install `sci-visualization/mricrogl-9999` (live version) directly via the gentoo package manager once you enable [the neurogentoo overlay](https://github.com/TheChymera/neurogentoo#install).

2) Ok, my bad, I only looked at the diagonal entries :-/

**Comment by neurolabusc** [comment]
1.) It looks like the OpenGL context has not yet been updated for GTK3. I have added a feature request for Lazarus.

/usr/share/lazarus/1.6/components/opengl/openglcontext.pas(71,4) Error: (2023) User defined: this LCL widgetset/OS is not yet supported

2.) I agree it would be nice to have better support of high resolution monitors and better DPI scaling. I have been really wrestling with the opposite problem: having a usable interface on screens with 1280x720 and 1024x768 resolutions. My current thought is to have a preference for allowing the toolbar to be wider, which would work well on high-resolution screens.

3.) Given that the overlap display problem reflects different spatial transforms I am going to close this issue, though I will contact you directly to try out my high-resolution beta release.

**Comment by TheChymera** [comment]
Thanks for being receptive to my suggestion. I'm happy to help you test any modifications out!

**Comment by neurolabusc** [comment]
I have sent an email to your private account. It includes a link for a GTK2 version that uses the same DPI scaling I use for Windows computers. Hopefully, this will allow you to use whatever size font you prefer.

**Comment by TheChymera** [comment]
I have not received anything. Was it by email? can you post the link here perhaps?

**Comment by neurolabusc** [comment]
I sent it to your email address. Here is the (temporary) download
https://www.dropbox.com/s/6c1cli8uuw4q5sh/scaling.tar.gz?dl=0

**Comment by TheChymera** [comment]
Finished downloading.

Do you have somethign similar for MRIcron?

**Comment by neurolabusc** [comment]
Yes,I have added the same patch to MRIcron, MRIcroGL and Surf Ice. You can try the MRIcron version here
  https://www.dropbox.com/s/2xxehdvpmdvzm00/mricron_lx.zip?dl=0

**Comment by TheChymera** [comment]
finished downloading that as well. I'll let you know when I get around to test them. Any special instructions from your side, or should they compile like the builds I packaged already?

**Comment by neurolabusc** [comment]
I uploaded the compiled executables, but as long as you download the updated code from Github they should just compile. Simply point lazbuild to the location of the lpr file for surface/MRIcron/MRIcroGL, e.g.
  lazbuild ./simplelaz.lpr
The code has compiler directives so that Windows will scale controls based on the reported screen DPI, Linux will scale controls based on the reported screen font size, and OSX allows retina resolution using the NSHighResolutionCapable key.
