### ISSUE TITLE
Plotting API

### ISSUE THREAD

**Issue by TheChymera** [neurolabusc/MRIcroGL#3]
Hi, I would be interested in using MRIcroGL to create figures as part of my data analysis scripts.

It does not seem like the program has an API. Do you think it would be worthwhile or feasible to create one?

lso, does MRIcroGL use conversion to VTK as an itermediary step to rendering?

**Comment by neurolabusc** [comment]
It has a built-in scripting language. You can use "savebmp" to save images and "quit" to terminate the program. This allows you to build scripts in any language, have the software generate your images and then exit once done. The web page includes many of the script that come with the software.
  http://www.mccauslandcenter.sc.edu/mricrogl/scripting
At the moment, you pass the path of an existing script, but in the next release I will add the ability to include a script in-line when you launch the program, similar to the Surf Ice Matlab and Python examples
  https://www.nitrc.org/plugins/mwiki/index.php/surfice:MainPage#Scripting_from_Matlab

**Comment by TheChymera** [comment]
So, based on the script example page, it looks like all of the scripts have to be selected via the GUI - right? Is there any way to pass the path to a script directly from the command line (and have the GUI not appear, or appear anc terminate in the background)?

**Comment by neurolabusc** [comment]
I have just uploaded a new version for you to experiment with that works just like Surf Ice, allowing you to adapt those Python and Matlab examples if you want. For example, you can pass a script as a command line argument:
  ./MRIcroGL -s "begin LOADIMAGE('chris_t1'); end."
Alternatively, you can pass the name of a script and it will be executed on launch. If no path is given it will look in your default scripting folder:
  ./MRIcroGL -s basic.gls
  ./MRIcroGL -s "Users/rorden/test.gls"
Note that with OSX you need to call the executable directly, not the .app package, for example on my computer the call would be
 /Users/rorden/Documents/OSX/MRIcroGL.app/Contents/MacOS/MRIcroGL -s basic.gls
Feel free to test this version and once we are happy with it I will release the executables on NITRC.

To have the application appear and then terminate once the script has completed simply add the "quit" command. For example this script should create a new bitmap on your desktop
  ./MRIcroGL -s "begin LOADIMAGE('mni152_2009bet'); savebmp('testing.png'); quit; end."

**Comment by thawhtetkaung** [comment]
I try to use `./MRIcroGL -s "begin LOADIMAGE('mni152_2009bet'); savebmp('testing.png'); quit; end."` from linux terminal but I got error.
`(MRIcroGL:4644): Gtk-WARNING **: cannot open display:`. I run it on my linux server. So there is no display mount. 
Is it possible to use or not. If it can, can you give me a reference.

**Comment by neurolabusc** [comment]
I suggest you look at the [troubleshooting](https://www.mccauslandcenter.sc.edu/mricrogl/troubleshooting) section. Usually running glxinfo from the command line will help. I usually run MRIcroGL on local machines, where you have direct access to a graphics card. However, for remote servers some have reported success with vglrun or Mesa. Note that [MRIcroGL 1.0](https://github.com/neurolabusc/MRIcroGL/releases) requires OpenGL 2.1 or later, while [MRIcroGL 1.2](https://github.com/rordenlab/MRIcroGL12/releases) requires OpenGL 3.3 or later. Note that you can run FSLeyes with OpenGL 1.4.

**Comment by thawhtetkaung** [comment]
Thank advance. But the problem is unsolved. The procedure I want to do is simple. All data are in my remote server. I want to call the MRIcroGL by using python subprocess. The work of MRIcroGL is simple.
Get data and convert to png. However, I got that   `(MRIcroGL:4644): Gtk-WARNING **: cannot open display:`. All process run on remote server. There is no interaction with my local PC and all I do is run that python script which locate on server over ssh.

Moreover, I got a window of application when I run on my local window pc. I don't want to pop up that application window and want to draw in memory.
Is MRIcroGL need to open a application window?

**Comment by neurolabusc** [comment]
Did you follow the advice on the troubleshooting page? What version was reported by glxinfo? Are you using vglrun or are you relying on Mesa? MRIcroGL requires an OpenGL context, and on Linux these are often tied to current screen resolution. For these reasons, it does not currently run in a completely headless form. It uses the OpenGL context for hardware accelerated features. The project is open source, so feel free to add features as you wish. If you wish to share new features with others, you can generate a pull request.

**Comment by thawhtetkaung** [comment]
My Bad!. My linux server has three gpu and use CUDA.  
I think that is the reason I can't use OpenGL.
Moreover, I tried to install mesa and try various solution, so the server can't open it Desktop. I doesn't know when it happen because I always work via ssh. So, I use other server use the solution from this link - https://gist.github.com/shehzan10/8d36c908af216573a1f0.
I can call glxinfo without error. But  it return no only OpenGL version but many text. 
Thanks for your support.
