### ISSUE TITLE
MRIcroGL no longer compiles

### ISSUE THREAD

**Issue by TheChymera** [neurolabusc/MRIcroGL#5]
Recently I tried to rebuild my live mricrogl version, and I got [this crash log](https://bpaste.net/show/1d5ba2ecc413). As you might notice, this is very resemblant of a [recent issue with mricron](https://github.com/neurolabusc/MRIcron/issues/3).

So I tried what you suggested there:
- `lazbuild -B --lazarusdir="/usr/share/lazarus/" simplelaz.lpi` works nicely in the cloned repo.
- `lazbuild -B --lazarusdir="/usr/share/lazarus/" simplelaz.lpi --ws=carbon` [fails](https://bpaste.net/show/f46bc9dcb4b9).
- `lazbuild -B --lazarusdir="/usr/share/lazarus/" simplelaz.lpi --ws=cocoa` [fails](https://bpaste.net/show/dcb0f80bc324).
- `lazbuild -B --lazarusdir="/usr/share/lazarus/" simplelaz.lpi --ws=gtk2` [fails](https://bpaste.net/show/d7d9963894cc).
- `lazbuild -B --lazarusdir="/usr/share/lazarus/" simplelaz.lpi --ws=gtk3` [fails](https://bpaste.net/show/956ad799185a).

**Comment by TheChymera** [comment]
I have `=lazarus-1.6.0-r1` and `=fpc-3.0.0`

**Comment by neurolabusc** [comment]
Hello,
  I can not give you a lot of help since I have moved to the Lazarus development branch (I am on Lazarus 1.7 revision 52666). Felipe has done a lot of work since 1.6 with respect to the OSX Cocoa widgetset. 
In any case, just looking at the error report it looks like the compiler is not finding MacOSAll.pas, so I would add the parent folder to your path.
